spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.clinicsaas: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    enabled: true
