ALTER TABLE tickets ADD COLUMN IF NOT EXISTS snoozed_until TIMESTAMP;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS snoozed_by_id UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS pre_snooze_status VARCHAR(20);
